### ISSUE TITLE
review and improvements to sql_database

### ISSUE THREAD

**Issue by rudolfix** [dlt-hub/pipelines#25]
@steinitzu thanks for the high quality work and your effort with testing! this looks amazing and I think at some point we'll move it to dlt-core sources...

here's my review (once #16  is merged)
1. please use ConnectionStringCredentials as a type for `database_url`
```
@dlt.source
def sql_database(
    database_url: str = dlt.secrets.value,
```
why?
users can pass a connection string (like now), a dict with parsed string (I can also support passing sqlalchemy engine directly - I do it for duckdb for eg.). on top of that dlt is able to reflect ConnectionStringCredentials (which is a dataclass) and generate secrets files and deployment configs automatically. I cannot do that for string
```
from dlt.common.configuration.specs import ConnectionStringCredentials
engine = create_engine(database_url.to_native_representation())
```
see also here: https://github.com/dlt-hub/dlt/blob/0.2.0a20/docs/examples/sources/sql_query.py#L59

2. You use batching in SqlAlchemy :thubsup:. Please do the same with dlt: you can actually return a list of rows in yield in `table_rows`. See here:
https://github.com/dlt-hub/dlt/blob/0.2.0a20/docs/examples/sources/jsonl.py#L10

3. I'd restrucutre code a little.
- there's @dlt.source for a database. this is good!

4. I'd add a standalone resource that you can use to query particular tables with a table specific settings (ie. write disposition, the cursor/uniq keys etc.)
example: https://github.com/dlt-hub/dlt/blob/0.2.0a20/docs/examples/sources/sql_query.py#L55 (also shows how to modify resource name/write disposition within @dlt.resource function)

both source and resource may use `table_rows` as generator.

note that you can pass a list of resources/sources/generators to dlt.run method so people can pick their own tables.

5. in
```
@dlt.source
def sql_database(
    database_url: ConnectionStringCredentials = dlt.secrets.value,
    schema: Optional[str] = dlt.config.value,
    table_names: Optional[List[str]] = dlt.config.value,
    write_disposition: str = 'replace',
) -> List[DltResource]:
```
write_disposition: str = 'replace' is not used at all. any plans for it?

6. I love the last value. I think this should be part of standard library (so you can decorate your resources with similar parameters). Here's my proposal how to structure it better
- new standalone resource can take those directly as arguments
- for the source where you create many tables, you can create "unbound resources" (https://github.com/dlt-hub/dlt/blob/devel/docs/technical/create_pipeline.md#unbound-parametrized-resources) that users can call later and pass additional settings. (probably you'll need to use partial). this is optional but interesting experiment.

7. metadata.reflect(bind=engine)
you should not reflect the whole database if `table_names` are provided. the code will be uglier... but reflection on certain databases costs.

8. code structure: I'd put the _make_query and cursor related code in a helper module. then the main module is easier to hack

------------------

tests:

1. please keep your fixtures with your tests - as long as we need to share them with other pipelines
2. use unique names for your schemas. test may be run in parallel on shared resources.
3. we need test cases for incremental load, for cases when you reflect tables or pass them directly etc.
4. we somehow need to test more sources. we can reuse destination credenitals (so we have ducdb, redshift, bigquery). I can set up MySQL in AWS
I'm not saying we shoudl do it now but please prepare your test so we can provide a list of connection strings to test against.

**Comment by rudolfix** [comment]
btw. I'm thinking of high performance database cloning with https://github.com/sfu-db/connector-x . we could replace the sqlalchemy with it even now but I'm not sure there will be much difference. it however can load directly to `arrow` tables and once `dlt` can process `arrow` natively I could use it to load data from db to db almost directly.

**Comment by steinitzu** [comment]
Amazing! Thank you for the detailed feedback. Will work on these.

**Comment by steinitzu** [comment]
> btw. I'm thinking of high performance database cloning with https://github.com/sfu-db/connector-x . we could replace the sqlalchemy with it even now but I'm not sure there will be much difference. it however can load directly to `arrow` tables and once `dlt` can process `arrow` natively I could use it to load data from db to db almost directly.

Nice, I didn't know about this. We could use both together I guess. SQLAlchemy for schema reflection and building queries, and connector-x to run them.

**Comment by rudolfix** [comment]
there are a few weird things about it:
1. it loads the whole data set and gives you panda frame or pyarrow. so requires more dependencies and more memory and will not work for big datasets
2. only a few sources are supported
3. bigquery credentials are passed as file so we should probably fallback to SqlAlchemy in that case

my take: if you want to experiment with it then great but I'd do it as an option or as a separate pipeline. just my 2c

**Comment by steinitzu** [comment]
@rudolfix Question about this:

> note that you can pass a list of resources/sources/generators to dlt.run method so people can pick their own tables.


This would be passed with calling `source().with_resources(...)`, right?  
Can this be handled lazily somehow? I can't find a way to access the resource list from within source.  
I'm thinking I need to know which tables are requested before generating the resources dynamically, so this could replace my `table_names` argument. So something like this where the source is a generator:    

```python3
@dlt.source
def sql_database(...):
    ...
    # Get arguments passed to `with_resource` from somewhere (if none do full schema reflection)   
    resource_names = get_requested_resources()

    # lazy generate resources
    for table in resource_names:
        yield dlt.source(table_rows ....)(...)
```
