### ISSUE TITLE
review and improvements to google sheets pipeline

### ISSUE THREAD

**Issue by rudolfix** [dlt-hub/pipelines#26]
**Motivation**
We look for a perfect balance between simplicity and feature richness in all our pipelines. That's because we want our users to be able to hack and customize them. Hacking means that the code of the pipeline itself will be changed to cover specific needs of particular user. We want to support that and make it easy - by writing clean and hackable code and proposing customizations as optional filters, transformations, settings etc.

**Current status**
We have two version of the google sheets pipeline:
* simple two-liner here: https://github.com/dlt-hub/dlt/blob/devel/docs/examples/sources/google_sheets.py
* a feature rich and well tested pipeline here: 
https://github.com/dlt-hub/pipelines/tree/master/pipelines/google_sheets
https://github.com/dlt-hub/pipelines/tree/master/tests/google_sheets
original ticket: https://github.com/dlt-hub/pipelines/issues/2

The problem with the first is that it is probably too simple: does not support datetime detection for example
The problem with second one is that it got too complicated to be hacked (IMHO)

**Task**
* Review code of both pipelines and propose or a new implementation or a set of improvements to existing ones
* Write your proposal as an issue here
* You can use any library you want
* Special wish: we want to support OAUTH authentication in a way that we can reuse in other pipelines (will be ported to `python-dlt` core at some point)
* Do it like you will implement it :)

**Comment by redicane** [comment]
Pipeline simplified with Pull Request: #55 now merged
