### ISSUE TITLE
Add examples to sql pipeline

### ISSUE THREAD

**Issue by adrianbr** [dlt-hub/pipelines#75]
As usage documentation, we need some examples in the SQL pipeline that show people how to configure the pipeline

Existing example: How to load all database 
usual use case
- Load some tables with "replace"
- load non stateful tables with "append"
- load some tables with merge

So we would like to show the following pipeline examples:
1. "load all tables" A case where we have a list of tables. The user will configure incremental loading for some tables and leave the rest to load as "replace"
2 "load selected tables" Same as before, but the user must specify "replace" tables as well, and anything else defaults to not load. 

We should demonstrate two methods:
1. with `sql_database` where we reflect the tables and selectively apply hints as specified above and load
2. with `sql_table` standalone resource where user knows the name of the tables and configures each one then loads together.

We may actually use one of public mysql databases as a demo source: ie. test `test_load_mysql_data_load` and 
```python
# reflect a database
credentials = ConnectionStringCredentials("mysql+pymysql://rfamro@mysql-rfam-public.ebi.ac.uk:4497/Rfam")
database = sql_database(credentials)
```
where we also demonstrate how to pass credentials explicitly...

**Comment by rudolfix** [comment]
Brute force way: we give you a `sql_table` standalone resource where you can define what you want. First you probably want to call `sql_database` to obtain a list of tables and then use that list to create particular resources. then you pass them as a list to `dlt.run` or as a list of tasks to airflow

Shortcuts: you want to add some tables as append and some as replace:
```
dlt.run(source.with_resources(a, b, c), write_disposition="replace)
dlt.run(source.with_resources(e, f, g), write_disposition="append)
```

other way: convert a single table to merge
we add primary keys automatically 
```
source.merge.table.apply_hints(write_disposition="merge", merge_key=.., )
dlt.run(source)
```

we do not have an easy way to do
source.incremental_table.incremental = dlt.source.incremental("created_at", initial,...) but we can add it

@steinitzu could we add write_disposition to `sql_database`?

**Comment by steinitzu** [comment]
Hi hi

> @steinitzu could we add write_disposition to sql_database?  

Yeah sure, you mean just to apply to all tables the same to start with?

**Comment by steinitzu** [comment]
The brute force way is super costly cause you end up reflecting the whole database in the source and also each table individually for the standalone resource.  
You can pass in your own engine and metadata and make it more efficient but that's more boilerplate.  

`apply_hints` looks sensible. We'll have to make it possible to override incremental somehow. Not really sure how to modify the injected argument/defer the resource call, using partials maybe? Or maybe the `resource.incremental` reference can be muated in place.

**Comment by rudolfix** [comment]
> Yeah sure, you mean just to apply to all tables the same to start with?
yeah

If you know the table names upfront then you can skip the `sql_database` altogether. I think in case Adrian is considering, the reflection of the database, even if done twice is negligible: tons of data will be synced using Airflow. If tables are known upfront then I think it is ok to do that.

I'm cracking my head how to add Incremental via `apply_hints`. I think we can still wrap a resource that accepts Incremental, in case of regular resource, incremental would still work - just it would read all the records again and filter the loaded ones. In case of `sql_databse` I assume it would work jus fine

**Comment by steinitzu** [comment]
> I'm cracking my head how to add Incremental via apply_hints. I think we can still wrap a resource that accepts Incremental, in case of regular resource, incremental would still work - just it would read all the records again and filter the loaded ones. In case of sql_databse I assume it would work jus fine  

Yeah it should work fine without injecting in this, I don't see why not. Just less performant.  
When there's already an injected arg we could just mutate it from `apply_hints` too, right? Could be better also to go back to what we had before where there is always a partial `Incremental` arg to edit.
