### ISSUE TITLE
Matomo basic pipeline

### ISSUE THREAD

**Issue by adrianbr** [dlt-hub/pipelines#77]
# Description
Matomo basic pipeline

# Use Cases
- Request tracking event data that was tracked with Matomo. I should have this data in a table that can be incremented on any schedule so I can keep it near live. I should be able to optionally also get the stateful user and update (merge) this data with events.
- Request aggregated report data on data tracked with Matomo. I expect this to always be aggregated on date, and incremented on date, so I can see the data up to end of yesterday, today. it is loaded incrementally in a nightly load.
- Request user defined report. I expect that it has a date column on which it is loaded incrementally in a nightly load.

# Sources / Resources / Endpoints
We want TWO sources with the folowing resources:

We want the sources to be split by schedule:
matomo_reports: Contains Reporting and Custom reporting
matomo_events: Contains events and dependent users

### Reporting resource
- we want the reporting api, the part where we can send a query and get back some data like in ga4
https://developer.matomo.org/api-reference/reporting-api
Requirements:
- Loading mode -  **let's always request date with our queries.** We want to load incrementally based on this date by using "append" mode based on last value. We should only load complete periods such as up till yesterday
- User should have some example queries he can issue
- User should be able to change the query
- we should increment on date by using the append/last value based increment described here https://dlthub.com/docs/general-usage/incremental-loading#incremental-loading-with-last-value

### Raw data "events"
- Raw data: https://developer.matomo.org/api-reference/reporting-api#Live we want this "raw data" api too - this should allow to export raw data from matomo
Resource:
-  Live.getLastVisitsDetails: Named "events" - This should be incremented as above. Always start from all time (which is a last 10d rss) and increment from last load.
-  Live.getVisitorProfile. named "visitors" This should be a dependent resource on events and request the profile for those users that showed up in the event increment. The visitors profile should be merged with each increment.

### Custom reports
We want to get custom reports too, as a method alternative to the first reports resource.
- CustomReports.getCustomReport (idSite, period, date, idCustomReport, segment = '', expanded = '', flat = '', idSubtable = '', columns = '') [ No example available ]
- I am not sure if we can get the report name automatically for the table name - if not provide the user with an option
- we can always request and increment on date so please use the same increment method as above.

# Customization
I believe there should be no customisation used for this pipeline. 
If it looks like we should use something, please notify the dlt team.

# Test account / test data
Use the public demo
https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?period=day&date=yesterday&category=Dashboard_Dashboard&subcategory=1

# Implementation tasks
Below you have a proposal for implementation tasks
* [ ] implement all the described sources, resources and endpoints
* [ ] make sure that the Use Cases can be easily executed by the user with the implemented by **providing demonstrations in all the use cases in the `[pipeline_name]_pipeline.py`
* [ ] all the use cases are tested
* [ ] if there are any customizations you must test them, including unit tests for custom code

**Comment by rudolfix** [comment]
@adrianbr this is really helpful but I'd still have a problem implementing it. Do you want to have three sources, one for each use cases:
- raw data (with all resources corresponding to live api endpoints)
- standard reports()
- custom reports ()

each of which could be used independently? You didn't specify that in sources. please try to add it.

**Comment by rudolfix** [comment]
done :)
